name: demo-action

on:
  push:
    branches: main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: run a sample
        run: echo Hello world 

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: ${{ github.workspace }}
  
  deploy:
    runs-on: windows-latest
    needs: build
    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
          path: ${{ github.workspace }}

      - name: Move artifact to local directory
        run: |
          mkdir -p C:\artifacts
          move "${{ github.workspace }}\output.txt" "C:\artifacts\output.txt"
        shell: powershell

    
